select * from BOARD;
select * from CATEGORY;
select * from Member;

SELECT CATEGORY_NAME 
FROM CATEGORY;
INSERT 
		INTO BOARD(
					BOARD_NO,
					BOARD_TYPE,
					CATEGORY_NO,
					BOARD_TITLE,
					BOARD_CONTENT,
					BOARD_WRITER
					)
			VALUES(
					SEQ_BNO.NEXTVAL,
					1,
					10,
					'안녕하세요',
					'안녕',
					1
			);

SELECT BOARD_NO,
			   CATEGORY_NAME,
               BOARD_TITLE,
               BOARD_CONTENT,
               MEMBER_ID,
               TO_CHAR(CREATE_DATE, 'YYYY/MM/DD') AS "CREATE_DATE"
          FROM BOARD
          LEFT JOIN CATEGORY USING(CATEGORY_NO)
          JOIN MEMBER ON(BOARD_WRITER = MEMBER_NO)
         WHERE BOARD_NO = 1;
         
 SELECT BOARD_NO,
		                   CATEGORY_NAME,
		                   BOARD_TITLE,
		                   MEMBER_ID,
		                   COUNT,
		                   TO_CHAR(CREATE_DATE, 'YYYY/MM/DD') AS "CREATE_DATE"
		              FROM BOARD B
		              JOIN CATEGORY USING(CATEGORY_NO)
		              JOIN MEMBER M ON(BOARD_WRITER = MEMBER_NO)
		             WHERE B.STATUS = 'Y'
		               AND BOARD_TYPE = 1
		             ORDER BY CREATE_DATE DESC;        
         
         
INSERT INTO BOARD (
    BOARD_NO,
    BOARD_TYPE,
    CATEGORY_NO,
    BOARD_TITLE,
    BOARD_CONTENT,
    BOARD_WRITER,
    COUNT,
    CREATE_DATE,
    STATUS
) VALUES (
    SEQ_BNO.NEXTVAL,     -- 게시글 번호
    1,                   -- 일반 게시판
    10,                   -- CATEGORY_NO 예시
    '첫 번째 게시글입니다.',
    '안녕하세요. 첫 번째 게시글의 내용입니다. 테스트용 데이터입니다.',
    1,                 -- 작성자: MEMBER.USER_NO 예시
    1,                  -- 조회수
    SYSDATE,         -- 작성일 (3일 전)
    'Y'                -- 활성 상태
                -- 대표 이미지 없음
);
INSERT INTO BOARD (
    BOARD_NO,
    BOARD_TYPE,
    CATEGORY_NO,
    BOARD_TITLE,
    BOARD_CONTENT,
    BOARD_WRITER,
    COUNT,
    CREATE_DATE,
    STATUS
) VALUES (
    SEQ_BNO.NEXTVAL,
    1,
    20,
    'Oracle 게시판 테스트 2 번째 글',
    '이 글은 Oracle 환경에서 작성된 더미데이터 예시입니다.',
    1,
    5,
    SYSDATE,
    'Y'
);

SELECT 
    B.BOARD_NO,
    B.CATEGORY_NO,
    B.BOARD_WRITER,
    C.CATEGORY_NO AS CAT_NO_IN_CATEGORY,
    M.MEMBER_NO   AS MEM_NO_IN_MEMBER
FROM BOARD B
LEFT JOIN CATEGORY C ON B.CATEGORY_NO = C.CATEGORY_NO
LEFT JOIN MEMBER M ON B.BOARD_WRITER = M.MEMBER_NO;

SELECT BOARD_NO, CATEGORY_NO, BOARD_WRITER, BOARD_TITLE, STATUS, BOARD_TYPE
    FROM BOARD;


SELECT * FROM BOARD B WHERE B.STATUS = 'Y' AND BOARD_TYPE = 1;
SELECT * FROM v$version;

SHOW CON_NAME;
SELECT SYS_CONTEXT('USERENV','CON_NAME') FROM DUAL;
SELECT SYS_CONTEXT('USERENV','DB_NAME') AS DB_NAME,
       SYS_CONTEXT('USERENV','CON_NAME') AS CON_NAME
FROM DUAL;
SHOW PDBS;
ALTER PLUGGABLE DATABASE ORCLPDB OPEN;
GRANT CREATE SESSION TO c##jsp;
GRANT CONNECT, RESOURCE TO c##jsp;

SELECT GRANTED_ROLE
FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'c##jsp';
SELECT PRIVILEGE
FROM DBA_SYS_PRIVS
WHERE GRANTEE = 'c##jsp';

SHOW CON_NAME;
SHOW PDBS;
ALTER SESSION SET CONTAINER=ORCLPDB;

CREATE USER C##JSP IDENTIFIED BY jsp CONTAINER=ALL;
GRANT CREATE SESSION TO C##JSP CONTAINER=ALL;
GRANT CONNECT, RESOURCE TO C##JSP CONTAINER=ALL;

SELECT SYS_CONTEXT('USERENV', 'CON_NAME') FROM DUAL;

SELECT TABLE_NAME FROM USER_TABLES;


INSERT INTO BOARD(BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER)
VALUES (SEQ_BNO.NEXTVAL, 1, 10, '게시글제목1', '게시글내용1', 1);

INSERT INTO BOARD(BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER)
VALUES (SEQ_BNO.NEXTVAL, 1, 20, '게시글제목2', '게시글내용2', 1);

INSERT INTO BOARD(BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER)
VALUES (SEQ_BNO.NEXTVAL, 1, 30, '게시글제목3', '게시글내용3', 2);

INSERT INTO BOARD(BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER)
VALUES (SEQ_BNO.NEXTVAL, 1, 40, '게시글제목4', '게시글내용4', 2);

INSERT INTO BOARD(BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER)
VALUES (SEQ_BNO.NEXTVAL, 1, 50, '게시글제목5', '게시글내용5', 3);

INSERT INTO BOARD(BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER)
VALUES (SEQ_BNO.NEXTVAL, 1, 10, '게시글제목6', '게시글내용6', 3);

INSERT INTO BOARD(BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER)
VALUES (SEQ_BNO.NEXTVAL, 1, 20, '게시글제목7', '게시글내용7', 4);

INSERT INTO BOARD(BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER)
VALUES (SEQ_BNO.NEXTVAL, 1, 30, '게시글제목8', '게시글내용8', 4);

INSERT INTO BOARD(BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER)
VALUES (SEQ_BNO.NEXTVAL, 1, 40, '게시글제목9', '게시글내용9', 5);

INSERT INTO BOARD(BOARD_NO, BOARD_TYPE, CATEGORY_NO, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER)
VALUES (SEQ_BNO.NEXTVAL, 1, 50, '게시글제목10', '게시글내용10', 5);


commit;